title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          type:
            type: text
      researchers:
        label: Researchers
        type: pages
        query: page.siblings(true)

  - width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        image:
          ratio: 1/1
