title: Project

columns:
  - width: 1/2
    fields:
      paragraph:
        type: writer
      gallery:
        type: files
        layout: cards
        image:
          ratio: 1/1
       pdf:
        label: Pdf
        type: files
  - width: 1/2
    sections:
      researchers:
        label: Researchers
        type: pages
        query: page.siblings(true)
